// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/

export const commands = {
  async greet(name: string): Promise<string> {
    return await TAURI_INVOKE('greet', { name })
  },
  async getConfig(): Promise<Config> {
    return await TAURI_INVOKE('get_config')
  },
  async saveConfig(config: Config): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('save_config', { config }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async login(username: string, password: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('login', { username, password }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getUserProfile(): Promise<Result<UserProfile, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_user_profile') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async searchByKeyword(
    keyword: string,
    pageNum: number,
    cateId: number | null,
    scanMode: string | null,
  ): Promise<Result<SearchResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('search_by_keyword', { keyword, pageNum, cateId, scanMode }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async searchByTag(
    tagName: string,
    pageNum: number,
    cateId: number | null,
    scanMode: string | null,
  ): Promise<Result<SearchResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('search_by_tag', { tagName, pageNum, cateId, scanMode }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async cancelScopedSearchScan(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('cancel_scoped_search_scan') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async advanceScopedSearchScan(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('advance_scoped_search_scan') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async browseByCategory(cateId: number, pageNum: number): Promise<Result<SearchResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('browse_by_category', { cateId, pageNum }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async browseRanking(
    period: RankingPeriod,
    cateId: number | null,
    pageNum: number,
  ): Promise<Result<SearchResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('browse_ranking', { period: String(period), cateId, pageNum }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async browseAlbumsList(pageNum: number): Promise<Result<SearchResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('browse_albums_list', { pageNum }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async browseHome(pageNum: number): Promise<Result<SearchResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('browse_home', { pageNum }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getComic(id: number): Promise<Result<Comic, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_comic', { id }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getComicTags(id: number): Promise<Result<Tag[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_comic_tags', { id }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getShelf(shelfId: number, pageNum: number): Promise<Result<GetShelfResult, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_shelf', { shelfId, pageNum }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async downloadShelf(shelfId: number): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('download_shelf', { shelfId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async createDownloadTask(comic: Comic, seriesParentDir?: string | null): Promise<void> {
    await TAURI_INVOKE('create_download_task', { comic, seriesParentDir: seriesParentDir ?? null })
  },
  async listSimilarKoreanSeriesFolders(
    seriesLabel: string,
    episodeStart: number,
    episodeEnd: number,
  ): Promise<Result<string[], CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('list_similar_korean_series_folders', {
          seriesLabel,
          episodeStart,
          episodeEnd,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async prepareKoreanSeriesFolder(
    seriesLabel: string,
    episodeStart: number,
    episodeEnd: number,
    existingFolderName?: string | null,
  ): Promise<Result<string, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('prepare_korean_series_folder', {
          seriesLabel,
          episodeStart,
          episodeEnd,
          existingFolderName: existingFolderName ?? null,
        }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async readKoreanTxtCatalog(catalogDir: string): Promise<Result<string[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('read_korean_txt_catalog', { catalogDir }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async pauseDownloadTask(comicId: number): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('pause_download_task', { comicId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async resumeDownloadTask(comicId: number): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('resume_download_task', { comicId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async cancelDownloadTask(comicId: number): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('cancel_download_task', { comicId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async removeDownloadTaskRecord(comicId: number): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('remove_download_task_record', { comicId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getDownloadTaskSnapshots(): Promise<Result<PersistedDownloadTask[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_download_task_snapshots') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getDownloadedComics(): Promise<Result<Comic[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_downloaded_comics') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getLogsDirSize(): Promise<Result<number, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_logs_dir_size') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async showPathInFileManager(path: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('show_path_in_file_manager', { path }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async showSnapshotDataFile(snapshotKind: 'global' | 'scoped'): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('show_snapshot_data_file', { snapshotKind }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async writeSnapshotExportFile(path: string, content: string): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('write_snapshot_export_file', { path, content }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async readSnapshotExportFile(path: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('read_snapshot_export_file', { path }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async writeSnapshotRepairFile(fileName: string, content: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('write_snapshot_repair_file', { fileName, content }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async writeSnapshotRootFile(fileName: string, content: string): Promise<Result<string, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('write_snapshot_root_file', { fileName, content }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async writeSnapshotWebsiteFile(
    fileName: string,
    content: string,
    deletePrevious?: boolean,
  ): Promise<Result<string, CommandError>> {
    try {
      return {
        status: 'ok',
        data: await TAURI_INVOKE('write_snapshot_website_file', { fileName, content, deletePrevious }),
      }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getCoverData(coverUrl: string): Promise<Result<number[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_cover_data', { coverUrl }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getReaderImage(comicId: number, imgUrl: string): Promise<Result<number[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_reader_image', { comicId, imgUrl }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async listLocalReaderSources(folderPath: string): Promise<Result<LocalReaderSource[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('list_local_reader_sources', { folderPath }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async loadLocalReaderPages(sourcePath: string): Promise<Result<LocalReaderPages, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('load_local_reader_pages', { sourcePath }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getLocalReaderImage(pageId: string): Promise<Result<number[], CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('get_local_reader_image', { pageId }) }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async closeLocalReaderZipSession(): Promise<Result<null, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('close_local_reader_zip_session') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
  async getRemoteManagementStatus(): Promise<RemoteManagementStatus> {
    return await TAURI_INVOKE('get_remote_management_status')
  },
  async restartRemoteManagement(): Promise<Result<RemoteManagementStatus, CommandError>> {
    try {
      return { status: 'ok', data: await TAURI_INVOKE('restart_remote_management') }
    } catch (e) {
      if (e instanceof Error) throw e
      else return { status: 'error', error: e as any }
    }
  },
}

/** user-defined events **/

export const events = __makeEvents__<{
  downloadShelfEvent: DownloadShelfEvent
  downloadSleepingEvent: DownloadSleepingEvent
  downloadSpeedEvent: DownloadSpeedEvent
  downloadTaskEvent: DownloadTaskEvent
  logEvent: LogEvent
  searchScanProgressEvent: SearchScanProgressEvent
}>({
  downloadShelfEvent: 'download-shelf-event',
  downloadSleepingEvent: 'download-sleeping-event',
  downloadSpeedEvent: 'download-speed-event',
  downloadTaskEvent: 'download-task-event',
  logEvent: 'log-event',
  searchScanProgressEvent: 'search-scan-progress-event',
})

/** user-defined constants **/

/** user-defined types **/

export type LocalReaderSourceKind = 'zip' | 'folder'
export type LocalReaderSource = { path: string; label: string; kind: LocalReaderSourceKind }
export type LocalReaderPage = { caption: string; pageId: string }
export type LocalReaderPages = { title: string; pages: LocalReaderPage[] }

export type ApiDomainMode = 'Default' | 'Custom'
export type Comic = {
  /**
   * 漫畫id
   */
  id: number
  /**
   * 漫畫標題
   */
  title: string
  /**
   * 封面鏈接
   */
  cover: string
  /**
   * 分類
   */
  category: string
  /**
   * 漫畫有多少張圖片
   */
  imageCount: number
  /**
   * 標籤
   */
  tags: Tag[]
  /**
   * 簡介
   */
  intro: string
  /**
   * 是否已下載
   */
  isDownloaded?: boolean | null
  /**
   * 圖片列表
   */
  imgList: ImgList
}
export type ComicInSearch = {
  /**
   * 漫畫id
   */
  id: number
  /**
   * 漫畫標題(帶html標籤，用於顯示匹配關鍵詞)
   */
  titleHtml: string
  /**
   * 漫畫標題
   */
  title: string
  /**
   * 封面鏈接
   */
  cover: string
  /**
   * 額外資訊(209張圖片， 創建於2025-01-05 18:33:19)
   */
  additionalInfo: string
  /**
   * 是否已下載
   */
  isDownloaded: boolean
  /**
   * 列表項上的官網分類 id（pic_box cate-{id}），用於分類內標籤篩選
   */
  listCateId: number | null
}
export type ComicInShelf = {
  /**
   * 漫畫id
   */
  id: number
  /**
   * 漫畫標題
   */
  title: string
  /**
   * 漫畫封面鏈接
   */
  cover: string
  /**
   * 加入書架的時間
   * 2025-01-04 16:04:34
   */
  favoriteTime: string
  /**
   * 這個漫畫屬於的書架
   */
  shelf: Shelf
  /**
   * 是否已下載
   */
  isDownloaded: boolean
}
export type CommandError = { err_title: string; err_message: string }
export type Config = {
  cookie: string
  downloadDir: string
  enableFileLogger: boolean
  downloadFormat: DownloadFormat
  proxyMode: ProxyMode
  proxyHost: string
  proxyPort: number
  comicConcurrency: number
  comicDownloadIntervalSec: number
  imgConcurrency: number
  imgDownloadIntervalSec: number
  downloadShelfIntervalMs: number
  batchDownloadIntervalMs: number
  useOriginalFilename: boolean
  apiDomainMode: ApiDomainMode
  customApiDomain: string
  downloadRetryCount: number
  downloadFailureRestSec: number
  koreanTxtCatalogDir: string
  koreanTxtDuplicateCheckEnabled: boolean
  remoteManagementEnabled: boolean
  remoteManagementDir: string
  remoteManagementShareSlots: number
  remoteManagementDirs: string[]
  remoteManagementPort: number
  remoteManagementToken: string
  remoteManagementDisplayName: string
}
export type RemoteManagementStatus = {
  enabled: boolean
  running: boolean
  httpReachable: boolean
  firewallReady: boolean
  firewallHint: string | null
  port: number
  displayName: string
  shareDir: string
  shareDirs: string[]
  lanAddresses: string[]
  lastError: string | null
}
export type DownloadFormat = 'JpegZipPack' | 'Server2Zip'
export type DownloadShelfEvent =
  | { event: 'GettingShelfComics' }
  | { event: 'CreatingDownloadTask'; data: { current: number; total: number } }
  | { event: 'End' }
export type DownloadSleepingEvent = { comicId: number; remainingSec: number }
export type DownloadSpeedEvent = { speed: string }
export type ZipDownloadServer = 'Server1' | 'Server2'
export type DownloadTaskEvent = {
  state: DownloadTaskState
  comic: Comic
  downloadedImgCount: number
  totalImgCount: number
  downloadPath?: string
  zipServer?: ZipDownloadServer
  downloadedBytes: number
  totalBytes: number
  seriesParentDir?: string
}
export type PersistedDownloadTask = {
  comicId: number
  comic: Comic
  state: DownloadTaskState
  seriesParentDir?: string
  downloadedImgCount: number
  totalImgCount: number
  downloadPath?: string
  zipServer?: ZipDownloadServer
  downloadedBytes: number
  totalBytes: number
}
export type DownloadTaskState = 'Pending' | 'Downloading' | 'Paused' | 'Cancelled' | 'Completed' | 'Failed'
export type GetShelfResult = {
  comics: ComicInShelf[]
  currentPage: number
  totalPage: number
  shelf: Shelf
  shelves: Shelf[]
}
export type ImgInImgList = {
  /**
   * 圖片標題([01]、[001]，根據漫畫總頁數確定)
   */
  caption: string
  /**
   * 圖片url(//img5.wnimg.ru/data/2826/33/01.jpg，缺https:前綴)
   * 最後一張圖片為/themes/weitu/images/bg/shoucang.jpg，記得過濾
   */
  url: string
}
export type ImgList = ImgInImgList[]
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type LogEvent = {
  timestamp: string
  level: LogLevel
  fields: Partial<{ [key in string]: JsonValue }>
  target: string
  filename: string
  line_number: number
}
export type LogLevel = 'TRACE' | 'DEBUG' | 'INFO' | 'WARN' | 'ERROR'
export type ProxyMode = 'System' | 'NoProxy' | 'Custom'
export type RankingPeriod = 'Day' | 'Week' | 'Month' | 'Year'
export type SearchScanProgressEvent = {
  current: number
  total: number
  matchedCount: number
  scanKind: string
  finished: boolean
  paused: boolean
  retryInSecs: number | null
  pausedReason: string | null
  cancelled: boolean
}
export type SearchResult = {
  comics: ComicInSearch[]
  currentPage: number
  totalPage: number
  totalCount: number
  isSearchByTag: boolean
}
export type Shelf = {
  /**
   * 書架id
   */
  id: number
  /**
   * 書架名稱
   */
  name: string
}
export type Tag = {
  /**
   * 標籤名
   */
  name: string
  /**
   * 標籤鏈接
   */
  url: string
}
export type UserProfile = {
  /**
   * 用戶名
   */
  username: string
  /**
   * 頭像url
   */
  avatar: string
}

/** tauri-specta globals **/

import { invoke as TAURI_INVOKE, Channel as TAURI_CHANNEL } from '@tauri-apps/api/core'
import * as TAURI_API_EVENT from '@tauri-apps/api/event'
import { type WebviewWindow as __WebviewWindow__ } from '@tauri-apps/api/webviewWindow'

type __EventObj__<T> = {
  listen: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.listen<T>>
  once: (cb: TAURI_API_EVENT.EventCallback<T>) => ReturnType<typeof TAURI_API_EVENT.once<T>>
  emit: null extends T
    ? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
    : (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>
}

export type Result<T, E> = { status: 'ok'; data: T } | { status: 'error'; error: E }

function __makeEvents__<T extends Record<string, any>>(mappings: Record<keyof T, string>) {
  return new Proxy(
    {} as unknown as {
      [K in keyof T]: __EventObj__<T[K]> & {
        (handle: __WebviewWindow__): __EventObj__<T[K]>
      }
    },
    {
      get: (_, event) => {
        const name = mappings[event as keyof T]

        return new Proxy((() => {}) as any, {
          apply: (_, __, [window]: [__WebviewWindow__]) => ({
            listen: (arg: any) => window.listen(name, arg),
            once: (arg: any) => window.once(name, arg),
            emit: (arg: any) => window.emit(name, arg),
          }),
          get: (_, command: keyof __EventObj__<any>) => {
            switch (command) {
              case 'listen':
                return (arg: any) => TAURI_API_EVENT.listen(name, arg)
              case 'once':
                return (arg: any) => TAURI_API_EVENT.once(name, arg)
              case 'emit':
                return (arg: any) => TAURI_API_EVENT.emit(name, arg)
            }
          },
        })
      },
    },
  )
}
